version: '3'

tasks:
  default:
    cmds:
      - task test
  test:
    cmds:
      - go test -v
    sources:
    - ./*.go
    method: none
  bench:
    cmds:
      - go test -v -bench=.
    sources:
      - ./*.go